packages:
  - apps/*
  - packages/*
  - extensions/*
  - ../Jaculus-tools/packages/*

ignoredBuiltDependencies:
  - '@playwright/browser-chromium'

allowBuilds:
  '@parcel/watcher': true
  '@serialport/bindings-cpp': true
  '@tailwindcss/oxide': true
  esbuild: true
  msw: true
