packages:
  - apps/*
  - packages/*
  - extensions/*
  - ../Jaculus-tools/packages/*

ignoredBuiltDependencies:
  - '@playwright/browser-chromium'
  - esbuild

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@serialport/bindings-cpp'
  - '@tailwindcss/oxide'
