import { createRouter } from '@tanstack/react-router';
import { routeTree } from '@/routeTree.gen'; // generated by TanStack Router plugin
import type { RouterContext } from './router-context';

export function makeRouter(context: RouterContext) {
  return createRouter({
    routeTree,
    context,
    defaultPreload: 'intent',
  });
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof makeRouter>;
  }
}
