export { BlocklyEditorPanel } from './blockly';
export { CodePanel } from './code';
export { ConsolePanel } from './console';
export { ErrorPanel } from './error';
export { GeneratedCode } from './generated-code';
export { InstallerPanel } from './installer';
export { JaculusPanel } from './jaculus';
export { LogsPanel } from './logs';
export { WokwiPanel } from './wokwi';
