import { createRouter } from '@tanstack/react-router';
import type { RouterContext } from './router-context';
import { routeTree } from '@/routeTree.gen'; // generated by TanStack Router plugin
import { deLocalizeUrl, localizeUrl } from "@/paraglide/runtime.js";

export function makeRouter(context: RouterContext) {
  return createRouter({
    routeTree,
    context,
    defaultPreload: 'intent',
    rewrite: {
      input: ({ url }) => deLocalizeUrl(url),
      output: ({ url }) => localizeUrl(url),
    }
  });
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof makeRouter>;
  }
}
